image: emilerolley/maven

lib-compile:
  stage: build
  script:
    - cd paleo-lib && mvn compile

lib-test:
  stage: test
  script:
    - cd paleo-lib && mvn compile test

lib-package:
  stage: deploy
  script:
    - cd paleo-lib && mvn package install

demo-compile:
  stage: build
  script:
    - make lib
    - cd paleo-demo && mvn compile

demo-test:
  stage: test
  script:
    - make lib
    - cd paleo-demo && mvn compile test

demo-assembly:
  stage: deploy
  script:
    - make lib
    - cd paleo-demo && mvn compile assembly:single
